
/***************************************************************************|
|                           UNIDADES - CFGPATCHES                           |
|***************************************************************************/

units[] = {
  "Item_U_B_CombatUniform_Digital", "Item_U_B_CombatUniform_Digital_Vest", "Item_U_B_CombatUniform_FCLA_Digital",
  "Item_U_B_CombatUniform_Takana_Digital", "Item_U_B_CombatUniform_Jaguar_Digital", "Item_U_B_CombatUniform_Condor_Digital",
  "Item_U_B_CombatUniform_Salamandra_Digital", "Item_U_B_CombatUniform_Anaconda_Digital", "Item_U_B_CombatUniform_Quetzal_Digital",
  "Item_U_B_CombatUniform_FCLA_Digital_Vest", "Item_U_B_CombatUniform_Takana_Digital_Vest", "Item_U_B_CombatUniform_Jaguar_Digital_Vest",
  "Item_U_B_CombatUniform_Condor_Digital_Vest", "Item_U_B_CombatUniform_Salamandra_Digital_Vest", "Item_U_B_CombatUniform_Anaconda_Digital_Vest", 
  "Item_U_B_CombatUniform_Quetzal_Digital_Vest", "Item_U_B_CombatUniform_Marine_v1", "Item_U_B_CombatUniform_Marine_v2",
  "Item_U_B_CombatUniform_Marine_Vest_v1", "Item_U_B_CombatUniform_Marine_Vest_v2", "Item_U_B_CombatUniform_FCLA_Marine_v1",
  "Item_U_B_CombatUniform_Takana_Marine_v1", "Item_U_B_CombatUniform_Jaguar_Marine_v1", "Item_U_B_CombatUniform_Condor_Marine_v1",
  "Item_U_B_CombatUniform_Salamandra_Marine_v1", "Item_U_B_CombatUniform_Anaconda_Marine_v1", "Item_U_B_CombatUniform_Quetzal_Marine_v1",
  "Item_U_B_CombatUniform_FCLA_Marine_Vest_v1", "Item_U_B_CombatUniform_Takana_Marine_Vest_v1", "Item_U_B_CombatUniform_Jaguar_Marine_Vest_v1",
  "Item_U_B_CombatUniform_Condor_Marine_Vest_v1", "Item_U_B_CombatUniform_Salamandra_Marine_Vest_v1", "Item_U_B_CombatUniform_Anaconda_Marine_Vest_v1",
  "Item_U_B_CombatUniform_Quetzal_Marine_Vest_v1", "Item_U_B_CombatUniform_Urban_v1", "Item_U_B_CombatUniform_Urban_v2",
  "Item_U_B_CombatUniform_Urban_v3", "Item_U_B_CombatUniform_Urban_v4", "Item_U_B_CombatUniform_Urban_Vest_v1",
  "Item_U_B_CombatUniform_Urban_Vest_v2", "Item_U_B_CombatUniform_Urban_Vest_v3", "Item_U_B_CombatUniform_Urban_Vest_v4",
  "Item_U_B_CombatUniform_FCLA_Urban_v1", "Item_U_B_CombatUniform_FCLA_Urban_v2", "Item_U_B_CombatUniform_Takana_Urban_v1",
  "Item_U_B_CombatUniform_Takana_Urban_v2", "Item_U_B_CombatUniform_Jaguar_Urban_v1", "Item_U_B_CombatUniform_Jaguar_Urban_v2",
  "Item_U_B_CombatUniform_Condor_Urban_v1", "Item_U_B_CombatUniform_Condor_Urban_v2", "Item_U_B_CombatUniform_Salamandra_Urban_v1",
  "Item_U_B_CombatUniform_Salamandra_Urban_v2", "Item_U_B_CombatUniform_Anaconda_Urban_v1", "Item_U_B_CombatUniform_Anaconda_Urban_v2",
  "Item_U_B_CombatUniform_Quetzal_Urban_v1", "Item_U_B_CombatUniform_Quetzal_Urban_v2", "Item_U_B_CombatUniform_FCLA_Urban_Vest_v1",
  "Item_U_B_CombatUniform_FCLA_Urban_Vest_v2", "Item_U_B_CombatUniform_Takana_Urban_Vest_v1", "Item_U_B_CombatUniform_Takana_Urban_Vest_v2",
  "Item_U_B_CombatUniform_Jaguar_Urban_Vest_v1", "Item_U_B_CombatUniform_Jaguar_Urban_Vest_v2", "Item_U_B_CombatUniform_Condor_Urban_Vest_v1",
  "Item_U_B_CombatUniform_Condor_Urban_Vest_v2", "Item_U_B_CombatUniform_Salamandra_Urban_Vest_v1", "Item_U_B_CombatUniform_Salamandra_Urban_Vest_v2",
  "Item_U_B_CombatUniform_Anaconda_Urban_Vest_v1", "Item_U_B_CombatUniform_Anaconda_Urban_Vest_v2", "Item_U_B_CombatUniform_Quetzal_Urban_Vest_v1",
  "Item_U_B_CombatUniform_Quetzal_Urban_Vest_v2", "Item_U_Recruiter", "Item_U_Instructor",
  "Item_U_B_CombatUniform_FCLA_mcam", "Item_U_B_CombatUniform_Takana_mcam", "Item_U_B_CombatUniform_Jaguar_mcam",
  "Item_U_B_CombatUniform_Condor_mcam", "Item_U_B_CombatUniform_Salamandra_mcam", "Item_U_B_CombatUniform_Anaconda_mcam",
  "Item_U_B_CombatUniform_Quetzal_mcam", "Item_U_B_CombatUniform_FCLA_Tropical", "Item_U_B_CombatUniform_Takana_Tropical",
  "Item_U_B_CombatUniform_Jaguar_Tropical", "Item_U_B_CombatUniform_Condor_Tropical", "Item_U_B_CombatUniform_Salamandra_Tropical",
  "Item_U_B_CombatUniform_Anaconda_Tropical", "Item_U_B_CombatUniform_Quetzal_Tropical", "Item_U_B_CombatUniform_FCLA_mcam_Vest",
  "Item_U_B_CombatUniform_Takana_mcam_Vest", "Item_U_B_CombatUniform_Jaguar_mcam_Vest", "Item_U_B_CombatUniform_Condor_mcam_Vest",
  "Item_U_B_CombatUniform_Salamandra_mcam_Vest", "Item_U_B_CombatUniform_Anaconda_mcam_Vest", "Item_U_B_CombatUniform_Quetzal_mcam_Vest",
  "Item_U_B_CombatUniform_FCLA_Tropical_Vest", "Item_U_B_CombatUniform_Takana_Tropical_Vest", "Item_U_B_CombatUniform_Jaguar_Tropical_Vest",
  "Item_U_B_CombatUniform_Condor_Tropical_Vest", "Item_U_B_CombatUniform_Salamandra_Tropical_Vest", "Item_U_B_CombatUniform_Anaconda_Tropical_Vest",
  "Item_U_B_CombatUniform_Quetzal_Tropical_Vest", "Item_U_B_HeliPilotCoveralls_FCLA", "Item_U_B_HeliPilotCoveralls_Quetzal",
  "Item_U_B_CombatUniform_Winter_v1", "Item_U_B_CombatUniform_Winter_v2", "Item_U_B_CombatUniform_Winter_v3",
  "Item_U_B_CombatUniform_Winter_Vest_v1", "Item_U_B_CombatUniform_Winter_Vest_v2", "Item_U_B_CombatUniform_Winter_Vest_v3",
  "Item_U_B_CombatUniform_FCLA_Winter_v1", "Item_U_B_CombatUniform_FCLA_Winter_v2", "Item_U_B_CombatUniform_FCLA_Winter_v3",
  "Item_U_B_CombatUniform_Takana_Winter_v1", "Item_U_B_CombatUniform_Takana_Winter_v2", "Item_U_B_CombatUniform_Takana_Winter_v3",
  "Item_U_B_CombatUniform_Jaguar_Winter_v1", "Item_U_B_CombatUniform_Jaguar_Winter_v2", "Item_U_B_CombatUniform_Jaguar_Winter_v3",
  "Item_U_B_CombatUniform_Condor_Winter_v1", "Item_U_B_CombatUniform_Condor_Winter_v2", "Item_U_B_CombatUniform_Condor_Winter_v3",
  "Item_U_B_CombatUniform_Salamandra_Winter_v1", "Item_U_B_CombatUniform_Salamandra_Winter_v2", "Item_U_B_CombatUniform_Salamandra_Winter_v3",
  "Item_U_B_CombatUniform_Anaconda_Winter_v1", "Item_U_B_CombatUniform_Anaconda_Winter_v2", "Item_U_B_CombatUniform_Anaconda_Winter_v3",
  "Item_U_B_CombatUniform_Quetzal_Winter_v1", "Item_U_B_CombatUniform_Quetzal_Winter_v2", "Item_U_B_CombatUniform_Quetzal_Winter_v3",
  "Item_U_B_CombatUniform_FCLA_Winter_Vest_v1", "Item_U_B_CombatUniform_FCLA_Winter_Vest_v2", "Item_U_B_CombatUniform_FCLA_Winter_Vest_v3",
  "Item_U_B_CombatUniform_Takana_Winter_Vest_v1", "Item_U_B_CombatUniform_Takana_Winter_Vest_v2", "Item_U_B_CombatUniform_Takana_Winter_Vest_v3",
  "Item_U_B_CombatUniform_Jaguar_Winter_Vest_v1", "Item_U_B_CombatUniform_Jaguar_Winter_Vest_v2", "Item_U_B_CombatUniform_Jaguar_Winter_Vest_v3",
  "Item_U_B_CombatUniform_Condor_Winter_Vest_v1", "Item_U_B_CombatUniform_Condor_Winter_Vest_v2", "Item_U_B_CombatUniform_Condor_Winter_Vest_v3",
  "Item_U_B_CombatUniform_Salamandra_Winter_Vest_v1", "Item_U_B_CombatUniform_Salamandra_Winter_Vest_v2", "Item_U_B_CombatUniform_Salamandra_Winter_Vest_v3",
  "Item_U_B_CombatUniform_Anaconda_Winter_Vest_v1", "Item_U_B_CombatUniform_Anaconda_Winter_Vest_v2", "Item_U_B_CombatUniform_Anaconda_Winter_Vest_v3",
  "Item_U_B_CombatUniform_Quetzal_Winter_Vest_v1", "Item_U_B_CombatUniform_Quetzal_Winter_Vest_v2", "Item_U_B_CombatUniform_Quetzal_Winter_Vest_v3"
};
