
/* ----------------------------------------------------------------------------
 * Author: hozlucas28
 *
 * Description:
 * Coloca el chaleco con la insignia a la unidad.
 *
 * Public: [No]
---------------------------------------------------------------------------- */

//Variables de referencia.
params ["_unit", "_insignia"];
_getPlatoon = [_insignia, (_insignia find "_") + 1, 100] call CBA_fnc_substring;
_platoon = if ((_getPlatoon == "Unassigned") || (_getPlatoon == "Common")) then {"FCLA";} else {_getPlatoon;};
_playerUID = getPlayerUID _unit;
_currentVest = vest _unit;
_itemsInVest = vestItems _unit;
_numberOfPlatoonLetters = count _platoon;



//Listado de chalecos con insignias.
_blackPlateCarrier = [
                      "V_PlateCarrier1_blk", "V_PlateCarrier_FCLA_Black", "V_PlateCarrier_Takana_Black", "V_PlateCarrier_Jaguar_Black", "V_PlateCarrier_Condor_Black", "V_PlateCarrier_Salamandra_Black", "V_PlateCarrier_Anaconda_Black", "V_PlateCarrier_Quetzal_Black",
                      "V_PlateCarrier_FCLA_Byron_Black", "V_PlateCarrier_Takana_Byron_Black", "V_PlateCarrier_Jaguar_Byron_Black", "V_PlateCarrier_Condor_Byron_Black", "V_PlateCarrier_Salamandra_Byron_Black", "V_PlateCarrier_Anaconda_Byron_Black", "V_PlateCarrier_Quetzal_Byron_Black",
                      "V_PlateCarrier_FCLA_Ghostkiller_Black", "V_PlateCarrier_Takana_Ghostkiller_Black", "V_PlateCarrier_Jaguar_Ghostkiller_Black", "V_PlateCarrier_Condor_Ghostkiller_Black", "V_PlateCarrier_Salamandra_Ghostkiller_Black", "V_PlateCarrier_Anaconda_Ghostkiller_Black", "V_PlateCarrier_Quetzal_Ghostkiller_Black",
                      "V_PlateCarrier_FCLA_hozLucas_Black", "V_PlateCarrier_Takana_hozLucas_Black", "V_PlateCarrier_Jaguar_hozLucas_Black", "V_PlateCarrier_Condor_hozLucas_Black", "V_PlateCarrier_Salamandra_hozLucas_Black", "V_PlateCarrier_Anaconda_hozLucas_Black", "V_PlateCarrier_Quetzal_hozLucas_Black",
                      "V_PlateCarrier_FCLA_Kovalsky_Black", "V_PlateCarrier_Takana_Kovalsky_Black", "V_PlateCarrier_Jaguar_Kovalsky_Black", "V_PlateCarrier_Condor_Kovalsky_Black", "V_PlateCarrier_Salamandra_Kovalsky_Black", "V_PlateCarrier_Anaconda_Kovalsky_Black", "V_PlateCarrier_Quetzal_Kovalsky_Black",
                      "V_PlateCarrier_FCLA_Legion_Black", "V_PlateCarrier_Takana_Legion_Black", "V_PlateCarrier_Jaguar_Legion_Black", "V_PlateCarrier_Condor_Legion_Black", "V_PlateCarrier_Salamandra_Legion_Black", "V_PlateCarrier_Anaconda_Legion_Black", "V_PlateCarrier_Quetzal_Legion_Black",
                      "V_PlateCarrier_FCLA_Lorflord_Black", "V_PlateCarrier_Takana_Lorflord_Black", "V_PlateCarrier_Jaguar_Lorflord_Black", "V_PlateCarrier_Condor_Lorflord_Black", "V_PlateCarrier_Salamandra_Lorflord_Black", "V_PlateCarrier_Anaconda_Lorflord_Black", "V_PlateCarrier_Quetzal_Lorflord_Black",
                      "V_PlateCarrier_FCLA_Mario_Black", "V_PlateCarrier_Takana_Mario_Black", "V_PlateCarrier_Jaguar_Mario_Black", "V_PlateCarrier_Condor_Mario_Black", "V_PlateCarrier_Salamandra_Mario_Black", "V_PlateCarrier_Anaconda_Mario_Black", "V_PlateCarrier_Quetzal_Mario_Black",
                      "V_PlateCarrier_FCLA_Naretick_Black", "V_PlateCarrier_Takana_Naretick_Black", "V_PlateCarrier_Jaguar_Naretick_Black", "V_PlateCarrier_Condor_Naretick_Black", "V_PlateCarrier_Salamandra_Naretick_Black", "V_PlateCarrier_Anaconda_Naretick_Black", "V_PlateCarrier_Quetzal_Naretick_Black",
                      "V_PlateCarrier_FCLA_Sagara_Black", "V_PlateCarrier_Takana_Sagara_Black", "V_PlateCarrier_Jaguar_Sagara_Black", "V_PlateCarrier_Condor_Sagara_Black", "V_PlateCarrier_Salamandra_Sagara_Black", "V_PlateCarrier_Anaconda_Sagara_Black", "V_PlateCarrier_Quetzal_Sagara_Black"
                     ];
_blackPlateCarrier2 = ["V_PlateCarrier2_blk", "V_PlateCarrier2_FCLA_Black", "V_PlateCarrier2_Takana_Black", "V_PlateCarrier2_Jaguar_Black", "V_PlateCarrier2_Condor_Black", "V_PlateCarrier2_Salamandra_Black", "V_PlateCarrier2_Anaconda_Black", "V_PlateCarrier2_Quetzal_Black"];
_greenPlateCarrier = [
                      "V_PlateCarrier1_rgr", "V_PlateCarrier1_rgr_noflag_F", "V_PlateCarrier_Kerry", "V_PlateCarrier_FCLA_Green", "V_PlateCarrier_Takana_Green", "V_PlateCarrier_Jaguar_Green", "V_PlateCarrier_Condor_Green", "V_PlateCarrier_Salamandra_Green", "V_PlateCarrier_Anaconda_Green", "V_PlateCarrier_Quetzal_Green",
                      "V_PlateCarrier_FCLA_Byron_Green", "V_PlateCarrier_Takana_Byron_Green", "V_PlateCarrier_Jaguar_Byron_Green", "V_PlateCarrier_Condor_Byron_Green", "V_PlateCarrier_Salamandra_Byron_Green", "V_PlateCarrier_Anaconda_Byron_Green", "V_PlateCarrier_Quetzal_Byron_Green",
                      "V_PlateCarrier_FCLA_Ghostkiller_Green", "V_PlateCarrier_Takana_Ghostkiller_Green", "V_PlateCarrier_Jaguar_Ghostkiller_Green", "V_PlateCarrier_Condor_Ghostkiller_Green", "V_PlateCarrier_Salamandra_Ghostkiller_Green", "V_PlateCarrier_Anaconda_Ghostkiller_Green", "V_PlateCarrier_Quetzal_Ghostkiller_Green",
                      "V_PlateCarrier_FCLA_hozLucas_Green", "V_PlateCarrier_Takana_hozLucas_Green", "V_PlateCarrier_Jaguar_hozLucas_Green", "V_PlateCarrier_Condor_hozLucas_Green", "V_PlateCarrier_Salamandra_hozLucas_Green", "V_PlateCarrier_Anaconda_hozLucas_Green", "V_PlateCarrier_Quetzal_hozLucas_Green",
                      "V_PlateCarrier_FCLA_Kovalsky_Green", "V_PlateCarrier_Takana_Kovalsky_Green", "V_PlateCarrier_Jaguar_Kovalsky_Green", "V_PlateCarrier_Condor_Kovalsky_Green", "V_PlateCarrier_Salamandra_Kovalsky_Green", "V_PlateCarrier_Anaconda_Kovalsky_Green", "V_PlateCarrier_Quetzal_Kovalsky_Green",
                      "V_PlateCarrier_FCLA_Legion_Green", "V_PlateCarrier_Takana_Legion_Green", "V_PlateCarrier_Jaguar_Legion_Green", "V_PlateCarrier_Condor_Legion_Green", "V_PlateCarrier_Salamandra_Legion_Green", "V_PlateCarrier_Anaconda_Legion_Green", "V_PlateCarrier_Quetzal_Legion_Green",
                      "V_PlateCarrier_FCLA_Lorflord_Green", "V_PlateCarrier_Takana_Lorflord_Green", "V_PlateCarrier_Jaguar_Lorflord_Green", "V_PlateCarrier_Condor_Lorflord_Green", "V_PlateCarrier_Salamandra_Lorflord_Green", "V_PlateCarrier_Anaconda_Lorflord_Green", "V_PlateCarrier_Quetzal_Lorflord_Green",
                      "V_PlateCarrier_FCLA_Mario_Green", "V_PlateCarrier_Takana_Mario_Green", "V_PlateCarrier_Jaguar_Mario_Green", "V_PlateCarrier_Condor_Mario_Green", "V_PlateCarrier_Salamandra_Mario_Green", "V_PlateCarrier_Anaconda_Mario_Green", "V_PlateCarrier_Quetzal_Mario_Green",
                      "V_PlateCarrier_FCLA_Naretick_Green", "V_PlateCarrier_Takana_Naretick_Green", "V_PlateCarrier_Jaguar_Naretick_Green", "V_PlateCarrier_Condor_Naretick_Green", "V_PlateCarrier_Salamandra_Naretick_Green", "V_PlateCarrier_Anaconda_Naretick_Green", "V_PlateCarrier_Quetzal_Naretick_Green",
                      "V_PlateCarrier_FCLA_Sagara_Green", "V_PlateCarrier_Takana_Sagara_Green", "V_PlateCarrier_Jaguar_Sagara_Green", "V_PlateCarrier_Condor_Sagara_Green", "V_PlateCarrier_Salamandra_Sagara_Green", "V_PlateCarrier_Anaconda_Sagara_Green", "V_PlateCarrier_Quetzal_Sagara_Green"
                     ];
_greenPlateCarrier2 = ["V_PlateCarrier2_rgr", "V_PlateCarrier2_rgr_noflag_F", "V_PlateCarrier2_FCLA_Green", "V_PlateCarrier2_Takana_Green", "V_PlateCarrier2_Jaguar_Green", "V_PlateCarrier2_Condor_Green", "V_PlateCarrier2_Salamandra_Green", "V_PlateCarrier2_Anaconda_Green", "V_PlateCarrier2_Quetzal_Green"];
_tropicalPlateCarrier = [
                         "V_PlateCarrier1_tna_F", "V_PlateCarrier_FCLA_Tropical", "V_PlateCarrier_Takana_Tropical", "V_PlateCarrier_Jaguar_Tropical", "V_PlateCarrier_Condor_Tropical", "V_PlateCarrier_Salamandra_Tropical", "V_PlateCarrier_Anaconda_Tropical", "V_PlateCarrier_Quetzal_Tropical",
                         "V_PlateCarrier_FCLA_Byron_Tropical", "V_PlateCarrier_Takana_Byron_Tropical", "V_PlateCarrier_Jaguar_Byron_Tropical", "V_PlateCarrier_Condor_Byron_Tropical", "V_PlateCarrier_Salamandra_Byron_Tropical", "V_PlateCarrier_Anaconda_Byron_Tropical", "V_PlateCarrier_Quetzal_Byron_Tropical",
                         "V_PlateCarrier_FCLA_Ghostkiller_Tropical", "V_PlateCarrier_Takana_Ghostkiller_Tropical", "V_PlateCarrier_Jaguar_Ghostkiller_Tropical", "V_PlateCarrier_Condor_Ghostkiller_Tropical", "V_PlateCarrier_Salamandra_Ghostkiller_Tropical", "V_PlateCarrier_Anaconda_Ghostkiller_Tropical", "V_PlateCarrier_Quetzal_Ghostkiller_Tropical",
                         "V_PlateCarrier_FCLA_hozLucas_Tropical", "V_PlateCarrier_Takana_hozLucas_Tropical", "V_PlateCarrier_Jaguar_hozLucas_Tropical", "V_PlateCarrier_Condor_hozLucas_Tropical", "V_PlateCarrier_Salamandra_hozLucas_Tropical", "V_PlateCarrier_Anaconda_hozLucas_Tropical", "V_PlateCarrier_Quetzal_hozLucas_Tropical",
                         "V_PlateCarrier_FCLA_Kovalsky_Tropical", "V_PlateCarrier_Takana_Kovalsky_Tropical", "V_PlateCarrier_Jaguar_Kovalsky_Tropical", "V_PlateCarrier_Condor_Kovalsky_Tropical", "V_PlateCarrier_Salamandra_Kovalsky_Tropical", "V_PlateCarrier_Anaconda_Kovalsky_Tropical", "V_PlateCarrier_Quetzal_Kovalsky_Tropical",
                         "V_PlateCarrier_FCLA_Legion_Tropical", "V_PlateCarrier_Takana_Legion_Tropical", "V_PlateCarrier_Jaguar_Legion_Tropical", "V_PlateCarrier_Condor_Legion_Tropical", "V_PlateCarrier_Salamandra_Legion_Tropical", "V_PlateCarrier_Anaconda_Legion_Tropical", "V_PlateCarrier_Quetzal_Legion_Tropical",
                         "V_PlateCarrier_FCLA_Lorflord_Tropical", "V_PlateCarrier_Takana_Lorflord_Tropical", "V_PlateCarrier_Jaguar_Lorflord_Tropical", "V_PlateCarrier_Condor_Lorflord_Tropical", "V_PlateCarrier_Salamandra_Lorflord_Tropical", "V_PlateCarrier_Anaconda_Lorflord_Tropical", "V_PlateCarrier_Quetzal_Lorflord_Tropical",
                         "V_PlateCarrier_FCLA_Mario_Tropical", "V_PlateCarrier_Takana_Mario_Tropical", "V_PlateCarrier_Jaguar_Mario_Tropical", "V_PlateCarrier_Condor_Mario_Tropical", "V_PlateCarrier_Salamandra_Mario_Tropical", "V_PlateCarrier_Anaconda_Mario_Tropical", "V_PlateCarrier_Quetzal_Mario_Tropical",
                         "V_PlateCarrier_FCLA_Naretick_Tropical", "V_PlateCarrier_Takana_Naretick_Tropical", "V_PlateCarrier_Jaguar_Naretick_Tropical", "V_PlateCarrier_Condor_Naretick_Tropical", "V_PlateCarrier_Salamandra_Naretick_Tropical", "V_PlateCarrier_Anaconda_Naretick_Tropical", "V_PlateCarrier_Quetzal_Naretick_Tropical",
                         "V_PlateCarrier_FCLA_Sagara_Tropical", "V_PlateCarrier_Takana_Sagara_Tropical", "V_PlateCarrier_Jaguar_Sagara_Tropical", "V_PlateCarrier_Condor_Sagara_Tropical", "V_PlateCarrier_Salamandra_Sagara_Tropical", "V_PlateCarrier_Anaconda_Sagara_Tropical", "V_PlateCarrier_Quetzal_Sagara_Tropical"
                        ];
_tropicalPlateCarrier2 = ["V_PlateCarrier2_tna_F", "V_PlateCarrier2_FCLA_Tropical", "V_PlateCarrier2_Takana_Tropical", "V_PlateCarrier2_Jaguar_Tropical", "V_PlateCarrier2_Condor_Tropical", "V_PlateCarrier2_Salamandra_Tropical", "V_PlateCarrier2_Anaconda_Tropical", "V_PlateCarrier2_Quetzal_Tropical"];
_digitalPlateCarrier = [
                        "V_PlateCarrier_Digital", "V_PlateCarrier_FCLA_Digital", "V_PlateCarrier_Takana_Digital", "V_PlateCarrier_Jaguar_Digital", "V_PlateCarrier_Condor_Digital", "V_PlateCarrier_Salamandra_Digital", "V_PlateCarrier_Anaconda_Digital", "V_PlateCarrier_Quetzal_Digital",
                        "V_PlateCarrier_FCLA_Byron_Digital", "V_PlateCarrier_Takana_Byron_Digital", "V_PlateCarrier_Jaguar_Byron_Digital", "V_PlateCarrier_Condor_Byron_Digital", "V_PlateCarrier_Salamandra_Byron_Digital", "V_PlateCarrier_Anaconda_Byron_Digital", "V_PlateCarrier_Quetzal_Byron_Digital",
                        "V_PlateCarrier_FCLA_Ghostkiller_Digital", "V_PlateCarrier_Takana_Ghostkiller_Digital", "V_PlateCarrier_Jaguar_Ghostkiller_Digital", "V_PlateCarrier_Condor_Ghostkiller_Digital", "V_PlateCarrier_Salamandra_Ghostkiller_Digital", "V_PlateCarrier_Anaconda_Ghostkiller_Digital", "V_PlateCarrier_Quetzal_Ghostkiller_Digital",
                        "V_PlateCarrier_FCLA_hozLucas_Digital", "V_PlateCarrier_Takana_hozLucas_Digital", "V_PlateCarrier_Jaguar_hozLucas_Digital", "V_PlateCarrier_Condor_hozLucas_Digital", "V_PlateCarrier_Salamandra_hozLucas_Digital", "V_PlateCarrier_Anaconda_hozLucas_Digital", "V_PlateCarrier_Quetzal_hozLucas_Digital",
                        "V_PlateCarrier_FCLA_Kovalsky_Digital", "V_PlateCarrier_Takana_Kovalsky_Digital", "V_PlateCarrier_Jaguar_Kovalsky_Digital", "V_PlateCarrier_Condor_Kovalsky_Digital", "V_PlateCarrier_Salamandra_Kovalsky_Digital", "V_PlateCarrier_Anaconda_Kovalsky_Digital", "V_PlateCarrier_Quetzal_Kovalsky_Digital",
                        "V_PlateCarrier_FCLA_Legion_Digital", "V_PlateCarrier_Takana_Legion_Digital", "V_PlateCarrier_Jaguar_Legion_Digital", "V_PlateCarrier_Condor_Legion_Digital", "V_PlateCarrier_Salamandra_Legion_Digital", "V_PlateCarrier_Anaconda_Legion_Digital", "V_PlateCarrier_Quetzal_Legion_Digital",
                        "V_PlateCarrier_FCLA_Lorflord_Digital", "V_PlateCarrier_Takana_Lorflord_Digital", "V_PlateCarrier_Jaguar_Lorflord_Digital", "V_PlateCarrier_Condor_Lorflord_Digital", "V_PlateCarrier_Salamandra_Lorflord_Digital", "V_PlateCarrier_Anaconda_Lorflord_Digital", "V_PlateCarrier_Quetzal_Lorflord_Digital",
                        "V_PlateCarrier_FCLA_Mario_Digital", "V_PlateCarrier_Takana_Mario_Digital", "V_PlateCarrier_Jaguar_Mario_Digital", "V_PlateCarrier_Condor_Mario_Digital", "V_PlateCarrier_Salamandra_Mario_Digital", "V_PlateCarrier_Anaconda_Mario_Digital", "V_PlateCarrier_Quetzal_Mario_Digital",
                        "V_PlateCarrier_FCLA_Naretick_Digital", "V_PlateCarrier_Takana_Naretick_Digital", "V_PlateCarrier_Jaguar_Naretick_Digital", "V_PlateCarrier_Condor_Naretick_Digital", "V_PlateCarrier_Salamandra_Naretick_Digital", "V_PlateCarrier_Anaconda_Naretick_Digital", "V_PlateCarrier_Quetzal_Naretick_Digital",
                        "V_PlateCarrier_FCLA_Sagara_Digital", "V_PlateCarrier_Takana_Sagara_Digital", "V_PlateCarrier_Jaguar_Sagara_Digital", "V_PlateCarrier_Condor_Sagara_Digital", "V_PlateCarrier_Salamandra_Sagara_Digital", "V_PlateCarrier_Anaconda_Sagara_Digital", "V_PlateCarrier_Quetzal_Sagara_Digital"
                       ];
_digitalPlateCarrier2 = ["V_PlateCarrier2_Digital", "V_PlateCarrier2_FCLA_Digital", "V_PlateCarrier2_Takana_Digital", "V_PlateCarrier2_Jaguar_Digital", "V_PlateCarrier2_Condor_Digital", "V_PlateCarrier2_Salamandra_Digital", "V_PlateCarrier2_Anaconda_Digital", "V_PlateCarrier2_Quetzal_Digital"];
_urbanV1PlateCarrier = [
                        "V_PlateCarrier_Urban_v1", "V_PlateCarrier_FCLA_Urban_v1", "V_PlateCarrier_Takana_Urban_v1", "V_PlateCarrier_Jaguar_Urban_v1", "V_PlateCarrier_Condor_Urban_v1", "V_PlateCarrier_Salamandra_Urban_v1", "V_PlateCarrier_Anaconda_Urban_v1", "V_PlateCarrier_Quetzal_Urban_v1",
                        "V_PlateCarrier_FCLA_Byron_Urban_v1", "V_PlateCarrier_Takana_Byron_Urban_v1", "V_PlateCarrier_Jaguar_Byron_Urban_v1", "V_PlateCarrier_Condor_Byron_Urban_v1", "V_PlateCarrier_Salamandra_Byron_Urban_v1", "V_PlateCarrier_Anaconda_Byron_Urban_v1", "V_PlateCarrier_Quetzal_Byron_Urban_v1",
                        "V_PlateCarrier_FCLA_Ghostkiller_Urban_v1", "V_PlateCarrier_Takana_Ghostkiller_Urban_v1", "V_PlateCarrier_Jaguar_Ghostkiller_Urban_v1", "V_PlateCarrier_Condor_Ghostkiller_Urban_v1", "V_PlateCarrier_Salamandra_Ghostkiller_Urban_v1", "V_PlateCarrier_Anaconda_Ghostkiller_Urban_v1", "V_PlateCarrier_Quetzal_Ghostkiller_Urban_v1",
                        "V_PlateCarrier_FCLA_hozLucas_Urban_v1", "V_PlateCarrier_Takana_hozLucas_Urban_v1", "V_PlateCarrier_Jaguar_hozLucas_Urban_v1", "V_PlateCarrier_Condor_hozLucas_Urban_v1", "V_PlateCarrier_Salamandra_hozLucas_Urban_v1", "V_PlateCarrier_Anaconda_hozLucas_Urban_v1", "V_PlateCarrier_Quetzal_hozLucas_Urban_v1",
                        "V_PlateCarrier_FCLA_Kovalsky_Urban_v1", "V_PlateCarrier_Takana_Kovalsky_Urban_v1", "V_PlateCarrier_Jaguar_Kovalsky_Urban_v1", "V_PlateCarrier_Condor_Kovalsky_Urban_v1", "V_PlateCarrier_Salamandra_Kovalsky_Urban_v1", "V_PlateCarrier_Anaconda_Kovalsky_Urban_v1", "V_PlateCarrier_Quetzal_Kovalsky_Urban_v1",
                        "V_PlateCarrier_FCLA_Legion_Urban_v1", "V_PlateCarrier_Takana_Legion_Urban_v1", "V_PlateCarrier_Jaguar_Legion_Urban_v1", "V_PlateCarrier_Condor_Legion_Urban_v1", "V_PlateCarrier_Salamandra_Legion_Urban_v1", "V_PlateCarrier_Anaconda_Legion_Urban_v1", "V_PlateCarrier_Quetzal_Legion_Urban_v1",
                        "V_PlateCarrier_FCLA_Lorflord_Urban_v1", "V_PlateCarrier_Takana_Lorflord_Urban_v1", "V_PlateCarrier_Jaguar_Lorflord_Urban_v1", "V_PlateCarrier_Condor_Lorflord_Urban_v1", "V_PlateCarrier_Salamandra_Lorflord_Urban_v1", "V_PlateCarrier_Anaconda_Lorflord_Urban_v1", "V_PlateCarrier_Quetzal_Lorflord_Urban_v1",
                        "V_PlateCarrier_FCLA_Mario_Urban_v1", "V_PlateCarrier_Takana_Mario_Urban_v1", "V_PlateCarrier_Jaguar_Mario_Urban_v1", "V_PlateCarrier_Condor_Mario_Urban_v1", "V_PlateCarrier_Salamandra_Mario_Urban_v1", "V_PlateCarrier_Anaconda_Mario_Urban_v1", "V_PlateCarrier_Quetzal_Mario_Urban_v1",
                        "V_PlateCarrier_FCLA_Naretick_Urban_v1", "V_PlateCarrier_Takana_Naretick_Urban_v1", "V_PlateCarrier_Jaguar_Naretick_Urban_v1", "V_PlateCarrier_Condor_Naretick_Urban_v1", "V_PlateCarrier_Salamandra_Naretick_Urban_v1", "V_PlateCarrier_Anaconda_Naretick_Urban_v1", "V_PlateCarrier_Quetzal_Naretick_Urban_v1",
                        "V_PlateCarrier_FCLA_Sagara_Urban_v1", "V_PlateCarrier_Takana_Sagara_Urban_v1", "V_PlateCarrier_Jaguar_Sagara_Urban_v1", "V_PlateCarrier_Condor_Sagara_Urban_v1", "V_PlateCarrier_Salamandra_Sagara_Urban_v1", "V_PlateCarrier_Anaconda_Sagara_Urban_v1", "V_PlateCarrier_Quetzal_Sagara_Urban_v1"
                       ];
_urbanV1PlateCarrier2 = ["V_PlateCarrier2_Urban_v1", "V_PlateCarrier2_FCLA_Urban_v1", "V_PlateCarrier2_Takana_Urban_v1", "V_PlateCarrier2_Jaguar_Urban_v1", "V_PlateCarrier2_Condor_Urban_v1", "V_PlateCarrier2_Salamandra_Urban_v1", "V_PlateCarrier2_Anaconda_Urban_v1", "V_PlateCarrier2_Quetzal_Urban_v1"];
_urbanV2PlateCarrier = [
                        "V_PlateCarrier_Urban_v2", "V_PlateCarrier_FCLA_Urban_v2", "V_PlateCarrier_Takana_Urban_v2", "V_PlateCarrier_Jaguar_Urban_v2", "V_PlateCarrier_Condor_Urban_v2", "V_PlateCarrier_Salamandra_Urban_v2", "V_PlateCarrier_Anaconda_Urban_v2", "V_PlateCarrier_Quetzal_Urban_v2",
                        "V_PlateCarrier_FCLA_Byron_Urban_v2", "V_PlateCarrier_Takana_Byron_Urban_v2", "V_PlateCarrier_Jaguar_Byron_Urban_v2", "V_PlateCarrier_Condor_Byron_Urban_v2", "V_PlateCarrier_Salamandra_Byron_Urban_v2", "V_PlateCarrier_Anaconda_Byron_Urban_v2", "V_PlateCarrier_Quetzal_Byron_Urban_v2",
                        "V_PlateCarrier_FCLA_Ghostkiller_Urban_v2", "V_PlateCarrier_Takana_Ghostkiller_Urban_v2", "V_PlateCarrier_Jaguar_Ghostkiller_Urban_v2", "V_PlateCarrier_Condor_Ghostkiller_Urban_v2", "V_PlateCarrier_Salamandra_Ghostkiller_Urban_v2", "V_PlateCarrier_Anaconda_Ghostkiller_Urban_v2", "V_PlateCarrier_Quetzal_Ghostkiller_Urban_v2",
                        "V_PlateCarrier_FCLA_hozLucas_Urban_v2", "V_PlateCarrier_Takana_hozLucas_Urban_v2", "V_PlateCarrier_Jaguar_hozLucas_Urban_v2", "V_PlateCarrier_Condor_hozLucas_Urban_v2", "V_PlateCarrier_Salamandra_hozLucas_Urban_v2", "V_PlateCarrier_Anaconda_hozLucas_Urban_v2", "V_PlateCarrier_Quetzal_hozLucas_Urban_v2",
                        "V_PlateCarrier_FCLA_Kovalsky_Urban_v2", "V_PlateCarrier_Takana_Kovalsky_Urban_v2", "V_PlateCarrier_Jaguar_Kovalsky_Urban_v2", "V_PlateCarrier_Condor_Kovalsky_Urban_v2", "V_PlateCarrier_Salamandra_Kovalsky_Urban_v2", "V_PlateCarrier_Anaconda_Kovalsky_Urban_v2", "V_PlateCarrier_Quetzal_Kovalsky_Urban_v2",
                        "V_PlateCarrier_FCLA_Legion_Urban_v2", "V_PlateCarrier_Takana_Legion_Urban_v2", "V_PlateCarrier_Jaguar_Legion_Urban_v2", "V_PlateCarrier_Condor_Legion_Urban_v2", "V_PlateCarrier_Salamandra_Legion_Urban_v2", "V_PlateCarrier_Anaconda_Legion_Urban_v2", "V_PlateCarrier_Quetzal_Legion_Urban_v2",
                        "V_PlateCarrier_FCLA_Lorflord_Urban_v2", "V_PlateCarrier_Takana_Lorflord_Urban_v2", "V_PlateCarrier_Jaguar_Lorflord_Urban_v2", "V_PlateCarrier_Condor_Lorflord_Urban_v2", "V_PlateCarrier_Salamandra_Lorflord_Urban_v2", "V_PlateCarrier_Anaconda_Lorflord_Urban_v2", "V_PlateCarrier_Quetzal_Lorflord_Urban_v2",
                        "V_PlateCarrier_FCLA_Mario_Urban_v2", "V_PlateCarrier_Takana_Mario_Urban_v2", "V_PlateCarrier_Jaguar_Mario_Urban_v2", "V_PlateCarrier_Condor_Mario_Urban_v2", "V_PlateCarrier_Salamandra_Mario_Urban_v2", "V_PlateCarrier_Anaconda_Mario_Urban_v2", "V_PlateCarrier_Quetzal_Mario_Urban_v2",
                        "V_PlateCarrier_FCLA_Naretick_Urban_v2", "V_PlateCarrier_Takana_Naretick_Urban_v2", "V_PlateCarrier_Jaguar_Naretick_Urban_v2", "V_PlateCarrier_Condor_Naretick_Urban_v2", "V_PlateCarrier_Salamandra_Naretick_Urban_v2", "V_PlateCarrier_Anaconda_Naretick_Urban_v2", "V_PlateCarrier_Quetzal_Naretick_Urban_v2",
                        "V_PlateCarrier_FCLA_Sagara_Urban_v2", "V_PlateCarrier_Takana_Sagara_Urban_v2", "V_PlateCarrier_Jaguar_Sagara_Urban_v2", "V_PlateCarrier_Condor_Sagara_Urban_v2", "V_PlateCarrier_Salamandra_Sagara_Urban_v2", "V_PlateCarrier_Anaconda_Sagara_Urban_v2", "V_PlateCarrier_Quetzal_Sagara_Urban_v2"
                       ];
_urbanV2PlateCarrier2 = ["V_PlateCarrier2_Urban_v2", "V_PlateCarrier2_FCLA_Urban_v2", "V_PlateCarrier2_Takana_Urban_v2", "V_PlateCarrier2_Jaguar_Urban_v2", "V_PlateCarrier2_Condor_Urban_v2", "V_PlateCarrier2_Salamandra_Urban_v2", "V_PlateCarrier2_Anaconda_Urban_v2", "V_PlateCarrier2_Quetzal_Urban_v2"];
_urbanV3PlateCarrier = [
                        "V_PlateCarrier_Urban_v3", "V_PlateCarrier_FCLA_Urban_v3", "V_PlateCarrier_Takana_Urban_v3", "V_PlateCarrier_Jaguar_Urban_v3", "V_PlateCarrier_Condor_Urban_v3", "V_PlateCarrier_Salamandra_Urban_v3", "V_PlateCarrier_Anaconda_Urban_v3", "V_PlateCarrier_Quetzal_Urban_v3",
                        "V_PlateCarrier_FCLA_Byron_Urban_v3", "V_PlateCarrier_Takana_Byron_Urban_v3", "V_PlateCarrier_Jaguar_Byron_Urban_v3", "V_PlateCarrier_Condor_Byron_Urban_v3", "V_PlateCarrier_Salamandra_Byron_Urban_v3", "V_PlateCarrier_Anaconda_Byron_Urban_v3", "V_PlateCarrier_Quetzal_Byron_Urban_v3",
                        "V_PlateCarrier_FCLA_Ghostkiller_Urban_v3", "V_PlateCarrier_Takana_Ghostkiller_Urban_v3", "V_PlateCarrier_Jaguar_Ghostkiller_Urban_v3", "V_PlateCarrier_Condor_Ghostkiller_Urban_v3", "V_PlateCarrier_Salamandra_Ghostkiller_Urban_v3", "V_PlateCarrier_Anaconda_Ghostkiller_Urban_v3", "V_PlateCarrier_Quetzal_Ghostkiller_Urban_v3",
                        "V_PlateCarrier_FCLA_hozLucas_Urban_v3", "V_PlateCarrier_Takana_hozLucas_Urban_v3", "V_PlateCarrier_Jaguar_hozLucas_Urban_v3", "V_PlateCarrier_Condor_hozLucas_Urban_v3", "V_PlateCarrier_Salamandra_hozLucas_Urban_v3", "V_PlateCarrier_Anaconda_hozLucas_Urban_v3", "V_PlateCarrier_Quetzal_hozLucas_Urban_v3",
                        "V_PlateCarrier_FCLA_Kovalsky_Urban_v3", "V_PlateCarrier_Takana_Kovalsky_Urban_v3", "V_PlateCarrier_Jaguar_Kovalsky_Urban_v3", "V_PlateCarrier_Condor_Kovalsky_Urban_v3", "V_PlateCarrier_Salamandra_Kovalsky_Urban_v3", "V_PlateCarrier_Anaconda_Kovalsky_Urban_v3", "V_PlateCarrier_Quetzal_Kovalsky_Urban_v3",
                        "V_PlateCarrier_FCLA_Legion_Urban_v3", "V_PlateCarrier_Takana_Legion_Urban_v3", "V_PlateCarrier_Jaguar_Legion_Urban_v3", "V_PlateCarrier_Condor_Legion_Urban_v3", "V_PlateCarrier_Salamandra_Legion_Urban_v3", "V_PlateCarrier_Anaconda_Legion_Urban_v3", "V_PlateCarrier_Quetzal_Legion_Urban_v3",
                        "V_PlateCarrier_FCLA_Lorflord_Urban_v3", "V_PlateCarrier_Takana_Lorflord_Urban_v3", "V_PlateCarrier_Jaguar_Lorflord_Urban_v3", "V_PlateCarrier_Condor_Lorflord_Urban_v3", "V_PlateCarrier_Salamandra_Lorflord_Urban_v3", "V_PlateCarrier_Anaconda_Lorflord_Urban_v3", "V_PlateCarrier_Quetzal_Lorflord_Urban_v3",
                        "V_PlateCarrier_FCLA_Mario_Urban_v3", "V_PlateCarrier_Takana_Mario_Urban_v3", "V_PlateCarrier_Jaguar_Mario_Urban_v3", "V_PlateCarrier_Condor_Mario_Urban_v3", "V_PlateCarrier_Salamandra_Mario_Urban_v3", "V_PlateCarrier_Anaconda_Mario_Urban_v3", "V_PlateCarrier_Quetzal_Mario_Urban_v3",
                        "V_PlateCarrier_FCLA_Naretick_Urban_v3", "V_PlateCarrier_Takana_Naretick_Urban_v3", "V_PlateCarrier_Jaguar_Naretick_Urban_v3", "V_PlateCarrier_Condor_Naretick_Urban_v3", "V_PlateCarrier_Salamandra_Naretick_Urban_v3", "V_PlateCarrier_Anaconda_Naretick_Urban_v3", "V_PlateCarrier_Quetzal_Naretick_Urban_v3",
                        "V_PlateCarrier_FCLA_Sagara_Urban_v3", "V_PlateCarrier_Takana_Sagara_Urban_v3", "V_PlateCarrier_Jaguar_Sagara_Urban_v3", "V_PlateCarrier_Condor_Sagara_Urban_v3", "V_PlateCarrier_Salamandra_Sagara_Urban_v3", "V_PlateCarrier_Anaconda_Sagara_Urban_v3", "V_PlateCarrier_Quetzal_Sagara_Urban_v3"
                       ];
_urbanV3PlateCarrier2 = ["V_PlateCarrier2_Urban_v3", "V_PlateCarrier2_FCLA_Urban_v3", "V_PlateCarrier2_Takana_Urban_v3", "V_PlateCarrier2_Jaguar_Urban_v3", "V_PlateCarrier2_Condor_Urban_v3", "V_PlateCarrier2_Salamandra_Urban_v3", "V_PlateCarrier2_Anaconda_Urban_v3", "V_PlateCarrier2_Quetzal_Urban_v3"];
_urbanV4PlateCarrier = [
                        "V_PlateCarrier_Urban_v4", "V_PlateCarrier_FCLA_Urban_v4", "V_PlateCarrier_Takana_Urban_v4", "V_PlateCarrier_Jaguar_Urban_v4", "V_PlateCarrier_Condor_Urban_v4", "V_PlateCarrier_Salamandra_Urban_v4", "V_PlateCarrier_Anaconda_Urban_v4", "V_PlateCarrier_Quetzal_Urban_v4",
                        "V_PlateCarrier_FCLA_Byron_Urban_v4", "V_PlateCarrier_Takana_Byron_Urban_v4", "V_PlateCarrier_Jaguar_Byron_Urban_v4", "V_PlateCarrier_Condor_Byron_Urban_v4", "V_PlateCarrier_Salamandra_Byron_Urban_v4", "V_PlateCarrier_Anaconda_Byron_Urban_v4", "V_PlateCarrier_Quetzal_Byron_Urban_v4",
                        "V_PlateCarrier_FCLA_Ghostkiller_Urban_v4", "V_PlateCarrier_Takana_Ghostkiller_Urban_v4", "V_PlateCarrier_Jaguar_Ghostkiller_Urban_v4", "V_PlateCarrier_Condor_Ghostkiller_Urban_v4", "V_PlateCarrier_Salamandra_Ghostkiller_Urban_v4", "V_PlateCarrier_Anaconda_Ghostkiller_Urban_v4", "V_PlateCarrier_Quetzal_Ghostkiller_Urban_v4",
                        "V_PlateCarrier_FCLA_hozLucas_Urban_v4", "V_PlateCarrier_Takana_hozLucas_Urban_v4", "V_PlateCarrier_Jaguar_hozLucas_Urban_v4", "V_PlateCarrier_Condor_hozLucas_Urban_v4", "V_PlateCarrier_Salamandra_hozLucas_Urban_v4", "V_PlateCarrier_Anaconda_hozLucas_Urban_v4", "V_PlateCarrier_Quetzal_hozLucas_Urban_v4",
                        "V_PlateCarrier_FCLA_Kovalsky_Urban_v4", "V_PlateCarrier_Takana_Kovalsky_Urban_v4", "V_PlateCarrier_Jaguar_Kovalsky_Urban_v4", "V_PlateCarrier_Condor_Kovalsky_Urban_v4", "V_PlateCarrier_Salamandra_Kovalsky_Urban_v4", "V_PlateCarrier_Anaconda_Kovalsky_Urban_v4", "V_PlateCarrier_Quetzal_Kovalsky_Urban_v4",
                        "V_PlateCarrier_FCLA_Legion_Urban_v4", "V_PlateCarrier_Takana_Legion_Urban_v4", "V_PlateCarrier_Jaguar_Legion_Urban_v4", "V_PlateCarrier_Condor_Legion_Urban_v4", "V_PlateCarrier_Salamandra_Legion_Urban_v4", "V_PlateCarrier_Anaconda_Legion_Urban_v4", "V_PlateCarrier_Quetzal_Legion_Urban_v4",
                        "V_PlateCarrier_FCLA_Lorflord_Urban_v4", "V_PlateCarrier_Takana_Lorflord_Urban_v4", "V_PlateCarrier_Jaguar_Lorflord_Urban_v4", "V_PlateCarrier_Condor_Lorflord_Urban_v4", "V_PlateCarrier_Salamandra_Lorflord_Urban_v4", "V_PlateCarrier_Anaconda_Lorflord_Urban_v4", "V_PlateCarrier_Quetzal_Lorflord_Urban_v4",
                        "V_PlateCarrier_FCLA_Mario_Urban_v4", "V_PlateCarrier_Takana_Mario_Urban_v4", "V_PlateCarrier_Jaguar_Mario_Urban_v4", "V_PlateCarrier_Condor_Mario_Urban_v4", "V_PlateCarrier_Salamandra_Mario_Urban_v4", "V_PlateCarrier_Anaconda_Mario_Urban_v4", "V_PlateCarrier_Quetzal_Mario_Urban_v4",
                        "V_PlateCarrier_FCLA_Naretick_Urban_v4", "V_PlateCarrier_Takana_Naretick_Urban_v4", "V_PlateCarrier_Jaguar_Naretick_Urban_v4", "V_PlateCarrier_Condor_Naretick_Urban_v4", "V_PlateCarrier_Salamandra_Naretick_Urban_v4", "V_PlateCarrier_Anaconda_Naretick_Urban_v4", "V_PlateCarrier_Quetzal_Naretick_Urban_v4",
                        "V_PlateCarrier_FCLA_Sagara_Urban_v4", "V_PlateCarrier_Takana_Sagara_Urban_v4", "V_PlateCarrier_Jaguar_Sagara_Urban_v4", "V_PlateCarrier_Condor_Sagara_Urban_v4", "V_PlateCarrier_Salamandra_Sagara_Urban_v4", "V_PlateCarrier_Anaconda_Sagara_Urban_v4", "V_PlateCarrier_Quetzal_Sagara_Urban_v4"
                       ];
_urbanV4PlateCarrier2 = ["V_PlateCarrier2_Urban_v4", "V_PlateCarrier2_FCLA_Urban_v4", "V_PlateCarrier2_Takana_Urban_v4", "V_PlateCarrier2_Jaguar_Urban_v4", "V_PlateCarrier2_Condor_Urban_v4", "V_PlateCarrier2_Salamandra_Urban_v4", "V_PlateCarrier2_Anaconda_Urban_v4", "V_PlateCarrier2_Quetzal_Urban_v4"];
_winterV1PlateCarrier = [
                         "V_PlateCarrier_Winter_v1", "V_PlateCarrier_FCLA_Winter_v1", "V_PlateCarrier_Takana_Winter_v1", "V_PlateCarrier_Jaguar_Winter_v1", "V_PlateCarrier_Condor_Winter_v1", "V_PlateCarrier_Salamandra_Winter_v1", "V_PlateCarrier_Anaconda_Winter_v1", "V_PlateCarrier_Quetzal_Winter_v1",
                         "V_PlateCarrier_FCLA_Byron_Winter_v1", "V_PlateCarrier_Takana_Byron_Winter_v1", "V_PlateCarrier_Jaguar_Byron_Winter_v1", "V_PlateCarrier_Condor_Byron_Winter_v1", "V_PlateCarrier_Salamandra_Byron_Winter_v1", "V_PlateCarrier_Anaconda_Byron_Winter_v1", "V_PlateCarrier_Quetzal_Byron_Winter_v1",
                         "V_PlateCarrier_FCLA_Ghostkiller_Winter_v1", "V_PlateCarrier_Takana_Ghostkiller_Winter_v1", "V_PlateCarrier_Jaguar_Ghostkiller_Winter_v1", "V_PlateCarrier_Condor_Ghostkiller_Winter_v1", "V_PlateCarrier_Salamandra_Ghostkiller_Winter_v1", "V_PlateCarrier_Anaconda_Ghostkiller_Winter_v1", "V_PlateCarrier_Quetzal_Ghostkiller_Winter_v1",
                         "V_PlateCarrier_FCLA_hozLucas_Winter_v1", "V_PlateCarrier_Takana_hozLucas_Winter_v1", "V_PlateCarrier_Jaguar_hozLucas_Winter_v1", "V_PlateCarrier_Condor_hozLucas_Winter_v1", "V_PlateCarrier_Salamandra_hozLucas_Winter_v1", "V_PlateCarrier_Anaconda_hozLucas_Winter_v1", "V_PlateCarrier_Quetzal_hozLucas_Winter_v1",
                         "V_PlateCarrier_FCLA_Kovalsky_Winter_v1", "V_PlateCarrier_Takana_Kovalsky_Winter_v1", "V_PlateCarrier_Jaguar_Kovalsky_Winter_v1", "V_PlateCarrier_Condor_Kovalsky_Winter_v1", "V_PlateCarrier_Salamandra_Kovalsky_Winter_v1", "V_PlateCarrier_Anaconda_Kovalsky_Winter_v1", "V_PlateCarrier_Quetzal_Kovalsky_Winter_v1",
                         "V_PlateCarrier_FCLA_Legion_Winter_v1", "V_PlateCarrier_Takana_Legion_Winter_v1", "V_PlateCarrier_Jaguar_Legion_Winter_v1", "V_PlateCarrier_Condor_Legion_Winter_v1", "V_PlateCarrier_Salamandra_Legion_Winter_v1", "V_PlateCarrier_Anaconda_Legion_Winter_v1", "V_PlateCarrier_Quetzal_Legion_Winter_v1",
                         "V_PlateCarrier_FCLA_Lorflord_Winter_v1", "V_PlateCarrier_Takana_Lorflord_Winter_v1", "V_PlateCarrier_Jaguar_Lorflord_Winter_v1", "V_PlateCarrier_Condor_Lorflord_Winter_v1", "V_PlateCarrier_Salamandra_Lorflord_Winter_v1", "V_PlateCarrier_Anaconda_Lorflord_Winter_v1", "V_PlateCarrier_Quetzal_Lorflord_Winter_v1",
                         "V_PlateCarrier_FCLA_Mario_Winter_v1", "V_PlateCarrier_Takana_Mario_Winter_v1", "V_PlateCarrier_Jaguar_Mario_Winter_v1", "V_PlateCarrier_Condor_Mario_Winter_v1", "V_PlateCarrier_Salamandra_Mario_Winter_v1", "V_PlateCarrier_Anaconda_Mario_Winter_v1", "V_PlateCarrier_Quetzal_Mario_Winter_v1",
                         "V_PlateCarrier_FCLA_Naretick_Winter_v1", "V_PlateCarrier_Takana_Naretick_Winter_v1", "V_PlateCarrier_Jaguar_Naretick_Winter_v1", "V_PlateCarrier_Condor_Naretick_Winter_v1", "V_PlateCarrier_Salamandra_Naretick_Winter_v1", "V_PlateCarrier_Anaconda_Naretick_Winter_v1", "V_PlateCarrier_Quetzal_Naretick_Winter_v1",
                         "V_PlateCarrier_FCLA_Sagara_Winter_v1", "V_PlateCarrier_Takana_Sagara_Winter_v1", "V_PlateCarrier_Jaguar_Sagara_Winter_v1", "V_PlateCarrier_Condor_Sagara_Winter_v1", "V_PlateCarrier_Salamandra_Sagara_Winter_v1", "V_PlateCarrier_Anaconda_Sagara_Winter_v1", "V_PlateCarrier_Quetzal_Sagara_Winter_v1"
                        ];
_winterV1PlateCarrier2 = ["V_PlateCarrier2_Winter_v1", "V_PlateCarrier2_FCLA_Winter_v1", "V_PlateCarrier2_Takana_Winter_v1", "V_PlateCarrier2_Jaguar_Winter_v1", "V_PlateCarrier2_Condor_Winter_v1", "V_PlateCarrier2_Salamandra_Winter_v1", "V_PlateCarrier2_Anaconda_Winter_v1", "V_PlateCarrier2_Quetzal_Winter_v1"];
_winterV2PlateCarrier = [
                         "V_PlateCarrier_Winter_v2", "V_PlateCarrier_FCLA_Winter_v2", "V_PlateCarrier_Takana_Winter_v2", "V_PlateCarrier_Jaguar_Winter_v2", "V_PlateCarrier_Condor_Winter_v2", "V_PlateCarrier_Salamandra_Winter_v2", "V_PlateCarrier_Anaconda_Winter_v2", "V_PlateCarrier_Quetzal_Winter_v2",
                         "V_PlateCarrier_FCLA_Byron_Winter_v2", "V_PlateCarrier_Takana_Byron_Winter_v2", "V_PlateCarrier_Jaguar_Byron_Winter_v2", "V_PlateCarrier_Condor_Byron_Winter_v2", "V_PlateCarrier_Salamandra_Byron_Winter_v2", "V_PlateCarrier_Anaconda_Byron_Winter_v2", "V_PlateCarrier_Quetzal_Byron_Winter_v2",
                         "V_PlateCarrier_FCLA_Ghostkiller_Winter_v2", "V_PlateCarrier_Takana_Ghostkiller_Winter_v2", "V_PlateCarrier_Jaguar_Ghostkiller_Winter_v2", "V_PlateCarrier_Condor_Ghostkiller_Winter_v2", "V_PlateCarrier_Salamandra_Ghostkiller_Winter_v2", "V_PlateCarrier_Anaconda_Ghostkiller_Winter_v2", "V_PlateCarrier_Quetzal_Ghostkiller_Winter_v2",
                         "V_PlateCarrier_FCLA_hozLucas_Winter_v2", "V_PlateCarrier_Takana_hozLucas_Winter_v2", "V_PlateCarrier_Jaguar_hozLucas_Winter_v2", "V_PlateCarrier_Condor_hozLucas_Winter_v2", "V_PlateCarrier_Salamandra_hozLucas_Winter_v2", "V_PlateCarrier_Anaconda_hozLucas_Winter_v2", "V_PlateCarrier_Quetzal_hozLucas_Winter_v2",
                         "V_PlateCarrier_FCLA_Kovalsky_Winter_v2", "V_PlateCarrier_Takana_Kovalsky_Winter_v2", "V_PlateCarrier_Jaguar_Kovalsky_Winter_v2", "V_PlateCarrier_Condor_Kovalsky_Winter_v2", "V_PlateCarrier_Salamandra_Kovalsky_Winter_v2", "V_PlateCarrier_Anaconda_Kovalsky_Winter_v2", "V_PlateCarrier_Quetzal_Kovalsky_Winter_v2",
                         "V_PlateCarrier_FCLA_Legion_Winter_v2", "V_PlateCarrier_Takana_Legion_Winter_v2", "V_PlateCarrier_Jaguar_Legion_Winter_v2", "V_PlateCarrier_Condor_Legion_Winter_v2", "V_PlateCarrier_Salamandra_Legion_Winter_v2", "V_PlateCarrier_Anaconda_Legion_Winter_v2", "V_PlateCarrier_Quetzal_Legion_Winter_v2",
                         "V_PlateCarrier_FCLA_Lorflord_Winter_v2", "V_PlateCarrier_Takana_Lorflord_Winter_v2", "V_PlateCarrier_Jaguar_Lorflord_Winter_v2", "V_PlateCarrier_Condor_Lorflord_Winter_v2", "V_PlateCarrier_Salamandra_Lorflord_Winter_v2", "V_PlateCarrier_Anaconda_Lorflord_Winter_v2", "V_PlateCarrier_Quetzal_Lorflord_Winter_v2",
                         "V_PlateCarrier_FCLA_Mario_Winter_v2", "V_PlateCarrier_Takana_Mario_Winter_v2", "V_PlateCarrier_Jaguar_Mario_Winter_v2", "V_PlateCarrier_Condor_Mario_Winter_v2", "V_PlateCarrier_Salamandra_Mario_Winter_v2", "V_PlateCarrier_Anaconda_Mario_Winter_v2", "V_PlateCarrier_Quetzal_Mario_Winter_v2",
                         "V_PlateCarrier_FCLA_Naretick_Winter_v2", "V_PlateCarrier_Takana_Naretick_Winter_v2", "V_PlateCarrier_Jaguar_Naretick_Winter_v2", "V_PlateCarrier_Condor_Naretick_Winter_v2", "V_PlateCarrier_Salamandra_Naretick_Winter_v2", "V_PlateCarrier_Anaconda_Naretick_Winter_v2", "V_PlateCarrier_Quetzal_Naretick_Winter_v2",
                         "V_PlateCarrier_FCLA_Sagara_Winter_v2", "V_PlateCarrier_Takana_Sagara_Winter_v2", "V_PlateCarrier_Jaguar_Sagara_Winter_v2", "V_PlateCarrier_Condor_Sagara_Winter_v2", "V_PlateCarrier_Salamandra_Sagara_Winter_v2", "V_PlateCarrier_Anaconda_Sagara_Winter_v2", "V_PlateCarrier_Quetzal_Sagara_Winter_v2"
                        ];
_winterV2PlateCarrier2 = ["V_PlateCarrier2_Winter_v2", "V_PlateCarrier2_FCLA_Winter_v2", "V_PlateCarrier2_Takana_Winter_v2", "V_PlateCarrier2_Jaguar_Winter_v2", "V_PlateCarrier2_Condor_Winter_v2", "V_PlateCarrier2_Salamandra_Winter_v2", "V_PlateCarrier2_Anaconda_Winter_v2", "V_PlateCarrier2_Quetzal_Winter_v2"];
_winterV3PlateCarrier = [
                         "V_PlateCarrier_Winter_v3", "V_PlateCarrier_FCLA_Winter_v3", "V_PlateCarrier_Takana_Winter_v3", "V_PlateCarrier_Jaguar_Winter_v3", "V_PlateCarrier_Condor_Winter_v3", "V_PlateCarrier_Salamandra_Winter_v3", "V_PlateCarrier_Anaconda_Winter_v3", "V_PlateCarrier_Quetzal_Winter_v3",
                         "V_PlateCarrier_FCLA_Byron_Winter_v3", "V_PlateCarrier_Takana_Byron_Winter_v3", "V_PlateCarrier_Jaguar_Byron_Winter_v3", "V_PlateCarrier_Condor_Byron_Winter_v3", "V_PlateCarrier_Salamandra_Byron_Winter_v3", "V_PlateCarrier_Anaconda_Byron_Winter_v3", "V_PlateCarrier_Quetzal_Byron_Winter_v3",
                         "V_PlateCarrier_FCLA_Ghostkiller_Winter_v3", "V_PlateCarrier_Takana_Ghostkiller_Winter_v3", "V_PlateCarrier_Jaguar_Ghostkiller_Winter_v3", "V_PlateCarrier_Condor_Ghostkiller_Winter_v3", "V_PlateCarrier_Salamandra_Ghostkiller_Winter_v3", "V_PlateCarrier_Anaconda_Ghostkiller_Winter_v3", "V_PlateCarrier_Quetzal_Ghostkiller_Winter_v3",
                         "V_PlateCarrier_FCLA_hozLucas_Winter_v3", "V_PlateCarrier_Takana_hozLucas_Winter_v3", "V_PlateCarrier_Jaguar_hozLucas_Winter_v3", "V_PlateCarrier_Condor_hozLucas_Winter_v3", "V_PlateCarrier_Salamandra_hozLucas_Winter_v3", "V_PlateCarrier_Anaconda_hozLucas_Winter_v3", "V_PlateCarrier_Quetzal_hozLucas_Winter_v3",
                         "V_PlateCarrier_FCLA_Kovalsky_Winter_v3", "V_PlateCarrier_Takana_Kovalsky_Winter_v3", "V_PlateCarrier_Jaguar_Kovalsky_Winter_v3", "V_PlateCarrier_Condor_Kovalsky_Winter_v3", "V_PlateCarrier_Salamandra_Kovalsky_Winter_v3", "V_PlateCarrier_Anaconda_Kovalsky_Winter_v3", "V_PlateCarrier_Quetzal_Kovalsky_Winter_v3",
                         "V_PlateCarrier_FCLA_Legion_Winter_v3", "V_PlateCarrier_Takana_Legion_Winter_v3", "V_PlateCarrier_Jaguar_Legion_Winter_v3", "V_PlateCarrier_Condor_Legion_Winter_v3", "V_PlateCarrier_Salamandra_Legion_Winter_v3", "V_PlateCarrier_Anaconda_Legion_Winter_v3", "V_PlateCarrier_Quetzal_Legion_Winter_v3",
                         "V_PlateCarrier_FCLA_Lorflord_Winter_v3", "V_PlateCarrier_Takana_Lorflord_Winter_v3", "V_PlateCarrier_Jaguar_Lorflord_Winter_v3", "V_PlateCarrier_Condor_Lorflord_Winter_v3", "V_PlateCarrier_Salamandra_Lorflord_Winter_v3", "V_PlateCarrier_Anaconda_Lorflord_Winter_v3", "V_PlateCarrier_Quetzal_Lorflord_Winter_v3",
                         "V_PlateCarrier_FCLA_Mario_Winter_v3", "V_PlateCarrier_Takana_Mario_Winter_v3", "V_PlateCarrier_Jaguar_Mario_Winter_v3", "V_PlateCarrier_Condor_Mario_Winter_v3", "V_PlateCarrier_Salamandra_Mario_Winter_v3", "V_PlateCarrier_Anaconda_Mario_Winter_v3", "V_PlateCarrier_Quetzal_Mario_Winter_v3",
                         "V_PlateCarrier_FCLA_Naretick_Winter_v3", "V_PlateCarrier_Takana_Naretick_Winter_v3", "V_PlateCarrier_Jaguar_Naretick_Winter_v3", "V_PlateCarrier_Condor_Naretick_Winter_v3", "V_PlateCarrier_Salamandra_Naretick_Winter_v3", "V_PlateCarrier_Anaconda_Naretick_Winter_v3", "V_PlateCarrier_Quetzal_Naretick_Winter_v3",
                         "V_PlateCarrier_FCLA_Sagara_Winter_v3", "V_PlateCarrier_Takana_Sagara_Winter_v3", "V_PlateCarrier_Jaguar_Sagara_Winter_v3", "V_PlateCarrier_Condor_Sagara_Winter_v3", "V_PlateCarrier_Salamandra_Sagara_Winter_v3", "V_PlateCarrier_Anaconda_Sagara_Winter_v3", "V_PlateCarrier_Quetzal_Sagara_Winter_v3"
                        ];
_winterV3PlateCarrier2 = ["V_PlateCarrier2_Winter_v3", "V_PlateCarrier2_FCLA_Winter_v3", "V_PlateCarrier2_Takana_Winter_v3", "V_PlateCarrier2_Jaguar_Winter_v3", "V_PlateCarrier2_Condor_Winter_v3", "V_PlateCarrier2_Salamandra_Winter_v3", "V_PlateCarrier2_Anaconda_Winter_v3", "V_PlateCarrier2_Quetzal_Winter_v3"];
_winterV4PlateCarrier = [
                         "V_PlateCarrier_Winter_v4", "V_PlateCarrier_FCLA_Winter_v4", "V_PlateCarrier_Takana_Winter_v4", "V_PlateCarrier_Jaguar_Winter_v4", "V_PlateCarrier_Condor_Winter_v4", "V_PlateCarrier_Salamandra_Winter_v4", "V_PlateCarrier_Anaconda_Winter_v4", "V_PlateCarrier_Quetzal_Winter_v4",
                         "V_PlateCarrier_FCLA_Byron_Winter_v4", "V_PlateCarrier_Takana_Byron_Winter_v4", "V_PlateCarrier_Jaguar_Byron_Winter_v4", "V_PlateCarrier_Condor_Byron_Winter_v4", "V_PlateCarrier_Salamandra_Byron_Winter_v4", "V_PlateCarrier_Anaconda_Byron_Winter_v4", "V_PlateCarrier_Quetzal_Byron_Winter_v4",
                         "V_PlateCarrier_FCLA_Ghostkiller_Winter_v4", "V_PlateCarrier_Takana_Ghostkiller_Winter_v4", "V_PlateCarrier_Jaguar_Ghostkiller_Winter_v4", "V_PlateCarrier_Condor_Ghostkiller_Winter_v4", "V_PlateCarrier_Salamandra_Ghostkiller_Winter_v4", "V_PlateCarrier_Anaconda_Ghostkiller_Winter_v4", "V_PlateCarrier_Quetzal_Ghostkiller_Winter_v4",
                         "V_PlateCarrier_FCLA_hozLucas_Winter_v4", "V_PlateCarrier_Takana_hozLucas_Winter_v4", "V_PlateCarrier_Jaguar_hozLucas_Winter_v4", "V_PlateCarrier_Condor_hozLucas_Winter_v4", "V_PlateCarrier_Salamandra_hozLucas_Winter_v4", "V_PlateCarrier_Anaconda_hozLucas_Winter_v4", "V_PlateCarrier_Quetzal_hozLucas_Winter_v4",
                         "V_PlateCarrier_FCLA_Kovalsky_Winter_v4", "V_PlateCarrier_Takana_Kovalsky_Winter_v4", "V_PlateCarrier_Jaguar_Kovalsky_Winter_v4", "V_PlateCarrier_Condor_Kovalsky_Winter_v4", "V_PlateCarrier_Salamandra_Kovalsky_Winter_v4", "V_PlateCarrier_Anaconda_Kovalsky_Winter_v4", "V_PlateCarrier_Quetzal_Kovalsky_Winter_v4",
                         "V_PlateCarrier_FCLA_Legion_Winter_v4", "V_PlateCarrier_Takana_Legion_Winter_v4", "V_PlateCarrier_Jaguar_Legion_Winter_v4", "V_PlateCarrier_Condor_Legion_Winter_v4", "V_PlateCarrier_Salamandra_Legion_Winter_v4", "V_PlateCarrier_Anaconda_Legion_Winter_v4", "V_PlateCarrier_Quetzal_Legion_Winter_v4",
                         "V_PlateCarrier_FCLA_Lorflord_Winter_v4", "V_PlateCarrier_Takana_Lorflord_Winter_v4", "V_PlateCarrier_Jaguar_Lorflord_Winter_v4", "V_PlateCarrier_Condor_Lorflord_Winter_v4", "V_PlateCarrier_Salamandra_Lorflord_Winter_v4", "V_PlateCarrier_Anaconda_Lorflord_Winter_v4", "V_PlateCarrier_Quetzal_Lorflord_Winter_v4",
                         "V_PlateCarrier_FCLA_Mario_Winter_v4", "V_PlateCarrier_Takana_Mario_Winter_v4", "V_PlateCarrier_Jaguar_Mario_Winter_v4", "V_PlateCarrier_Condor_Mario_Winter_v4", "V_PlateCarrier_Salamandra_Mario_Winter_v4", "V_PlateCarrier_Anaconda_Mario_Winter_v4", "V_PlateCarrier_Quetzal_Mario_Winter_v4",
                         "V_PlateCarrier_FCLA_Naretick_Winter_v4", "V_PlateCarrier_Takana_Naretick_Winter_v4", "V_PlateCarrier_Jaguar_Naretick_Winter_v4", "V_PlateCarrier_Condor_Naretick_Winter_v4", "V_PlateCarrier_Salamandra_Naretick_Winter_v4", "V_PlateCarrier_Anaconda_Naretick_Winter_v4", "V_PlateCarrier_Quetzal_Naretick_Winter_v4",
                         "V_PlateCarrier_FCLA_Sagara_Winter_v4", "V_PlateCarrier_Takana_Sagara_Winter_v4", "V_PlateCarrier_Jaguar_Sagara_Winter_v4", "V_PlateCarrier_Condor_Sagara_Winter_v4", "V_PlateCarrier_Salamandra_Sagara_Winter_v4", "V_PlateCarrier_Anaconda_Sagara_Winter_v4", "V_PlateCarrier_Quetzal_Sagara_Winter_v4"
                        ];
_winterV4PlateCarrier2 = ["V_PlateCarrier2_Winter_v4", "V_PlateCarrier2_FCLA_Winter_v4", "V_PlateCarrier2_Takana_Winter_v4", "V_PlateCarrier2_Jaguar_Winter_v4", "V_PlateCarrier2_Condor_Winter_v4", "V_PlateCarrier2_Salamandra_Winter_v4", "V_PlateCarrier2_Anaconda_Winter_v4", "V_PlateCarrier2_Quetzal_Winter_v4"];
_marinePlateCarrier = [
                       "V_PlateCarrier_Marine", "V_PlateCarrier_FCLA_Marine", "V_PlateCarrier_Takana_Marine", "V_PlateCarrier_Jaguar_Marine", "V_PlateCarrier_Condor_Marine", "V_PlateCarrier_Salamandra_Marine", "V_PlateCarrier_Anaconda_Marine", "V_PlateCarrier_Quetzal_Marine",
                       "V_PlateCarrier_FCLA_Byron_Marine", "V_PlateCarrier_Takana_Byron_Marine", "V_PlateCarrier_Jaguar_Byron_Marine", "V_PlateCarrier_Condor_Byron_Marine", "V_PlateCarrier_Salamandra_Byron_Marine", "V_PlateCarrier_Anaconda_Byron_Marine", "V_PlateCarrier_Quetzal_Byron_Marine",
                       "V_PlateCarrier_FCLA_Ghostkiller_Marine", "V_PlateCarrier_Takana_Ghostkiller_Marine", "V_PlateCarrier_Jaguar_Ghostkiller_Marine", "V_PlateCarrier_Condor_Ghostkiller_Marine", "V_PlateCarrier_Salamandra_Ghostkiller_Marine", "V_PlateCarrier_Anaconda_Ghostkiller_Marine", "V_PlateCarrier_Quetzal_Ghostkiller_Marine",
                       "V_PlateCarrier_FCLA_hozLucas_Marine", "V_PlateCarrier_Takana_hozLucas_Marine", "V_PlateCarrier_Jaguar_hozLucas_Marine", "V_PlateCarrier_Condor_hozLucas_Marine", "V_PlateCarrier_Salamandra_hozLucas_Marine", "V_PlateCarrier_Anaconda_hozLucas_Marine", "V_PlateCarrier_Quetzal_hozLucas_Marine",
                       "V_PlateCarrier_FCLA_Kovalsky_Marine", "V_PlateCarrier_Takana_Kovalsky_Marine", "V_PlateCarrier_Jaguar_Kovalsky_Marine", "V_PlateCarrier_Condor_Kovalsky_Marine", "V_PlateCarrier_Salamandra_Kovalsky_Marine", "V_PlateCarrier_Anaconda_Kovalsky_Marine", "V_PlateCarrier_Quetzal_Kovalsky_Marine",
                       "V_PlateCarrier_FCLA_Legion_Marine", "V_PlateCarrier_Takana_Legion_Marine", "V_PlateCarrier_Jaguar_Legion_Marine", "V_PlateCarrier_Condor_Legion_Marine", "V_PlateCarrier_Salamandra_Legion_Marine", "V_PlateCarrier_Anaconda_Legion_Marine", "V_PlateCarrier_Quetzal_Legion_Marine",
                       "V_PlateCarrier_FCLA_Lorflord_Marine", "V_PlateCarrier_Takana_Lorflord_Marine", "V_PlateCarrier_Jaguar_Lorflord_Marine", "V_PlateCarrier_Condor_Lorflord_Marine", "V_PlateCarrier_Salamandra_Lorflord_Marine", "V_PlateCarrier_Anaconda_Lorflord_Marine", "V_PlateCarrier_Quetzal_Lorflord_Marine",
                       "V_PlateCarrier_FCLA_Mario_Marine", "V_PlateCarrier_Takana_Mario_Marine", "V_PlateCarrier_Jaguar_Mario_Marine", "V_PlateCarrier_Condor_Mario_Marine", "V_PlateCarrier_Salamandra_Mario_Marine", "V_PlateCarrier_Anaconda_Mario_Marine", "V_PlateCarrier_Quetzal_Mario_Marine",
                       "V_PlateCarrier_FCLA_Naretick_Marine", "V_PlateCarrier_Takana_Naretick_Marine", "V_PlateCarrier_Jaguar_Naretick_Marine", "V_PlateCarrier_Condor_Naretick_Marine", "V_PlateCarrier_Salamandra_Naretick_Marine", "V_PlateCarrier_Anaconda_Naretick_Marine", "V_PlateCarrier_Quetzal_Naretick_Marine",
                       "V_PlateCarrier_FCLA_Sagara_Marine", "V_PlateCarrier_Takana_Sagara_Marine", "V_PlateCarrier_Jaguar_Sagara_Marine", "V_PlateCarrier_Condor_Sagara_Marine", "V_PlateCarrier_Salamandra_Sagara_Marine", "V_PlateCarrier_Anaconda_Sagara_Marine", "V_PlateCarrier_Quetzal_Sagara_Marine"
                      ];
_marinePlateCarrier2 = ["V_PlateCarrier2_Marine", "V_PlateCarrier2_FCLA_Marine", "V_PlateCarrier2_Takana_Marine", "V_PlateCarrier2_Jaguar_Marine", "V_PlateCarrier2_Condor_Marine", "V_PlateCarrier2_Salamandra_Marine", "V_PlateCarrier2_Anaconda_Marine", "V_PlateCarrier2_Quetzal_Marine"];
_blackPlateCarrierSpec = ["V_PlateCarrierSpec_blk", "V_PlateCarrierSpec_FCLA_Black", "V_PlateCarrierSpec_Takana_Black", "V_PlateCarrierSpec_Jaguar_Black", "V_PlateCarrierSpec_Condor_Black", "V_PlateCarrierSpec_Salamandra_Black", "V_PlateCarrierSpec_Anaconda_Black", "V_PlateCarrierSpec_Quetzal_Black"];
_MTPPlateCarrierSpec = ["V_PlateCarrierSpec_mtp", "V_PlateCarrierSpec_FCLA_MTP", "V_PlateCarrierSpec_Takana_MTP", "V_PlateCarrierSpec_Jaguar_MTP", "V_PlateCarrierSpec_Condor_MTP", "V_PlateCarrierSpec_Salamandra_MTP", "V_PlateCarrierSpec_Anaconda_MTP", "V_PlateCarrierSpec_Quetzal_MTP"];
_greenPlateCarrierSpec = ["V_PlateCarrierSpec_rgr", "V_PlateCarrierSpec_FCLA_Green", "V_PlateCarrierSpec_Takana_Green", "V_PlateCarrierSpec_Jaguar_Green", "V_PlateCarrierSpec_Condor_Green", "V_PlateCarrierSpec_Salamandra_Green", "V_PlateCarrierSpec_Anaconda_Green", "V_PlateCarrierSpec_Quetzal_Green"];
_tropicalPlateCarrierSpec = ["V_PlateCarrierSpec_tna_F", "V_PlateCarrierSpec_FCLA_Tropical", "V_PlateCarrierSpec_Takana_Tropical", "V_PlateCarrierSpec_Jaguar_Tropical", "V_PlateCarrierSpec_Condor_Tropical", "V_PlateCarrierSpec_Salamandra_Tropical", "V_PlateCarrierSpec_Anaconda_Tropical", "V_PlateCarrierSpec_Quetzal_Tropical"];
_blackPlateCarrierGL = ["V_PlateCarrierGL_blk", "V_PlateCarrierGL_FCLA_Black", "V_PlateCarrierGL_Takana_Black", "V_PlateCarrierGL_Jaguar_Black", "V_PlateCarrierGL_Condor_Black", "V_PlateCarrierGL_Salamandra_Black", "V_PlateCarrierGL_Anaconda_Black", "V_PlateCarrierGL_Quetzal_Black"];
_MTPPlateCarrierGL = ["V_PlateCarrierGL_mtp", "V_PlateCarrierGL_FCLA_MTP", "V_PlateCarrierGL_Takana_MTP", "V_PlateCarrierGL_Jaguar_MTP", "V_PlateCarrierGL_Condor_MTP", "V_PlateCarrierGL_Salamandra_MTP", "V_PlateCarrierGL_Anaconda_MTP", "V_PlateCarrierGL_Quetzal_MTP"];
_greenPlateCarrierGL = ["V_PlateCarrierGL_rgr", "V_PlateCarrierGL_FCLA_Green", "V_PlateCarrierGL_Takana_Green", "V_PlateCarrierGL_Jaguar_Green", "V_PlateCarrierGL_Condor_Green", "V_PlateCarrierGL_Salamandra_Green", "V_PlateCarrierGL_Anaconda_Green", "V_PlateCarrierGL_Quetzal_Green"];
_tropicalPlateCarrierGL = ["V_PlateCarrierGL_tna_F", "V_PlateCarrierGL_FCLA_Tropical", "V_PlateCarrierGL_Takana_Tropical", "V_PlateCarrierGL_Jaguar_Tropical", "V_PlateCarrierGL_Condor_Tropical", "V_PlateCarrierGL_Salamandra_Tropical", "V_PlateCarrierGL_Anaconda_Tropical", "V_PlateCarrierGL_Quetzal_Tropical"];
_EODPlateCarrier = ["V_EOD_olive_F", "V_EOD_FCLA", "V_EOD_Takana", "V_EOD_Jaguar", "V_EOD_Condor", "V_EOD_Salamandra", "V_EOD_Anaconda", "V_EOD_Quetzal"];


//Obtener chaleco con insignia.
_vestWithInsignia = switch (true) do {
	case (_currentVest in _blackPlateCarrier): {"V_PlateCarrier_" + _platoon + "_Black";};
  case (_currentVest in _blackPlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Black";};
  case (_currentVest in _greenPlateCarrier): {"V_PlateCarrier_" + _platoon + "_Green";};
  case (_currentVest in _greenPlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Green";};
  case (_currentVest in _tropicalPlateCarrier): {"V_PlateCarrier_" + _platoon + "_Tropical";};
  case (_currentVest in _tropicalPlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Tropical";};
  case (_currentVest in _digitalPlateCarrier): {"V_PlateCarrier_" + _platoon + "_Digital";};
  case (_currentVest in _digitalPlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Digital";};
  case (_currentVest in _urbanV1PlateCarrier): {"V_PlateCarrier_" + _platoon + "_Urban_v1";};
  case (_currentVest in _urbanV1PlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Urban_v1";};
  case (_currentVest in _urbanV2PlateCarrier): {"V_PlateCarrier_" + _platoon + "_Urban_v2";};
  case (_currentVest in _urbanV2PlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Urban_v2";};
  case (_currentVest in _urbanV3PlateCarrier): {"V_PlateCarrier_" + _platoon + "_Urban_v3";};
  case (_currentVest in _urbanV3PlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Urban_v3";};
  case (_currentVest in _urbanV4PlateCarrier): {"V_PlateCarrier_" + _platoon + "_Urban_v4";};
  case (_currentVest in _urbanV4PlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Urban_v4";};
  case (_currentVest in _winterV1PlateCarrier): {"V_PlateCarrier_" + _platoon + "_Winter_v1";};
  case (_currentVest in _winterV1PlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Winter_v1";};
  case (_currentVest in _winterV2PlateCarrier): {"V_PlateCarrier_" + _platoon + "_Winter_v2";};
  case (_currentVest in _winterV2PlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Winter_v2";};
  case (_currentVest in _winterV3PlateCarrier): {"V_PlateCarrier_" + _platoon + "_Winter_v3";};
  case (_currentVest in _winterV3PlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Winter_v3";};
  case (_currentVest in _winterV4PlateCarrier): {"V_PlateCarrier_" + _platoon + "_Winter_v4";};
  case (_currentVest in _winterV4PlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Winter_v4";};
  case (_currentVest in _marinePlateCarrier): {"V_PlateCarrier_" + _platoon + "_Marine";};
  case (_currentVest in _marinePlateCarrier2): {"V_PlateCarrier2_" + _platoon + "_Marine";};
  case (_currentVest in _blackPlateCarrierSpec): {"V_PlateCarrierSpec_" + _platoon + "_Black";};
  case (_currentVest in _MTPPlateCarrierSpec): {"V_PlateCarrierSpec_" + _platoon + "_MTP";};
  case (_currentVest in _greenPlateCarrierSpec): {"V_PlateCarrierSpec_" + _platoon + "_Green";};
  case (_currentVest in _tropicalPlateCarrierSpec): {"V_PlateCarrierSpec_" + _platoon + "_Tropical";};
  case (_currentVest in _blackPlateCarrierGL): {"V_PlateCarrierGL_" + _platoon + "_Black";};
  case (_currentVest in _MTPPlateCarrierGL): {"V_PlateCarrierGL_" + _platoon + "_MTP";};
  case (_currentVest in _greenPlateCarrierGL): {"V_PlateCarrierGL_" + _platoon + "_Green";};
  case (_currentVest in _tropicalPlateCarrierGL): {"V_PlateCarrierGL_" + _platoon + "_Tropical";};
  case (_currentVest in _EODPlateCarrier): {"V_EOD_" + _platoon;};
	default {"";};
};


//Obtener chaleco personalizado.
_customVestWithInsignia = switch (_playerUID) do {
	case "76561198178496662": {_vestWithInsignia insert [(_vestWithInsignia find _platoon) + _numberOfPlatoonLetters, "_Byron"];;};
	case "76561198304995327": {_vestWithInsignia insert [(_vestWithInsignia find _platoon) + _numberOfPlatoonLetters, "_Ghostkiller"];;};
	case "76561198137876583": {_vestWithInsignia insert [(_vestWithInsignia find _platoon) + _numberOfPlatoonLetters, "_hozLucas"];;};
	case "76561198010584812": {_vestWithInsignia insert [(_vestWithInsignia find _platoon) + _numberOfPlatoonLetters, "_Kovalsky"];;};
	case "76561197982853635": {_vestWithInsignia insert [(_vestWithInsignia find _platoon) + _numberOfPlatoonLetters, "_Legion"];;};
	case "76561198153898683": {_vestWithInsignia insert [(_vestWithInsignia find _platoon) + _numberOfPlatoonLetters, "_Lorflord"];;};
	case "76561198260536786": {_vestWithInsignia insert [(_vestWithInsignia find _platoon) + _numberOfPlatoonLetters, "_Mario"];;};
	case "76561198059595506": {_vestWithInsignia insert [(_vestWithInsignia find _platoon) + _numberOfPlatoonLetters, "_Naretick"];;};
	case "76561198173170422": {_vestWithInsignia insert [(_vestWithInsignia find _platoon) + _numberOfPlatoonLetters, "_Sagara"];;};
	default {_vestWithInsignia;};
};


//Colocar chaleco.
_selectedVest = if (isClass (configFile >> "CfgWeapons" >> _customVestWithInsignia)) then {_customVestWithInsignia;} else {_vestWithInsignia;};
if ((_currentVest == _selectedVest) || !(isClass (configFile >> "CfgWeapons" >> _selectedVest))) exitWith {};
removeVest _unit;
_unit addVest _selectedVest;
{_unit addItemToVest _x} forEach _itemsInVest;
